[access]
token = "53d86cc809090ee047cf343fd787888e"

[rpc]
listen = ":9091"

[cert]
key_file = "cert/server.key"
crt_file = "cert/server.pem"

[log]
level="debug"
filename="log/access.log"
maxSize=1048576
maxLine=1000000
dateSlice="d"
jsonFormat=true

[log.levelFilename]
error="log/error.log"
info="log/info.log"